# Generated by Django 5.0.1 on 2024-01-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(max_length=25, verbose_name="Nombre de usuario"),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                (
                    "password",
                    models.CharField(max_length=50, verbose_name="Contraseña"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                ("user_is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
